[package]
name = "unyt_chain_transaction"
version = "0.1.0"
edition.workspace = true
build = "../scenario_build.rs"
publish = false

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
rmp-serde = "1.3.0"
reqwest = { version = "0.12", features = ["json"] }
semver = "1.0.10"

holochain_types = { workspace = true }
holochain_serialized_bytes = { workspace = true }
holochain_wind_tunnel_runner = { workspace = true }

rave_engine = { workspace = true }
zfuel = { workspace = true }

[build-dependencies]
happ_builder = { workspace = true }

[lints]
workspace = true

[package.metadata.fetch-required-happ]
name = "unyt"
url = "https://github.com/unytco/unyt-sandbox/releases/download/v0.50.0/unyt.happ"
sha256 = "77aa53bd9c549da6b4b259dd4e09fdd146d6f6c078640240c8324d47da1ac929"
