[package]
name = "write_validated_must_get_agent_activity"
version = "0.1.0"
edition.workspace = true
build = "../scenario_build.rs"
publish = false

[dependencies]
anyhow = { workspace = true }
holochain_types = { workspace = true }
holochain_wind_tunnel_runner = { workspace = true }
log = "0.4.29"
validated_must_get_agent_activity = { path = "../../zomes/validated_must_get_agent_activity/coordinator" }

[build-dependencies]
happ_builder = { workspace = true }

[lints]
workspace = true

[package.metadata.required-dna]
name = "validated_must_get_agent_activity"
zomes = ["validated_must_get_agent_activity"]

[package.metadata.required-happ]
name = "validated_must_get_agent_activity"
dnas = ["validated_must_get_agent_activity"]
