[package]
name = "timed_and_validated"
version = "0.1.0"
edition.workspace = true
description = "A Holochain coordinator zome for timing data visibility, with validation"
publish = false

[lib]
name = "timed_and_validated_coordinator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
timed_and_validated_integrity = { workspace = true }

[lints]
workspace = true
