name: "Run Nomad Scenario"

on:
  workflow_call:
    inputs:
      holochain-bin-url:
        description: "The URL to download the `holochain` binary from"
        type: string
        required: true
      commit-hash:
        description: "The git commit hash to checkout before running the tests"
        type: string
        required: false
      nomad-job-variant-directory:
        description: "The path to the directory containing the nomad job variant"
        type: string
        required: true
      enable-summary-uploads:
        description: "Enable upload of summary visualiser html to GitHub Pages and summary json to bucket"
        type: boolean
        required: true
      ignore-summary-errors:
        description: "Ignore errors from summarizer"
        type: boolean
        required: true
    secrets:
      NOMAD_ACCESS_TOKEN:
        required: true
      INFLUX_TOKEN:
        required: true
      HETZNER_HOLOCHAIN_INFRA_BUCKETS_ACCESS:
        required: true
      HETZNER_HOLOCHAIN_INFRA_BUCKETS_SECRET:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  run-scenarios:
    name: Run ${{ matrix.job-name }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        job-name:
          - first_call
          - local_signals
          - remote_call_rate
          - remote_signals
          - single_write_many_read
          - write_query
          - write_read
          - write_validated
          - zome_call_single_value
          - app_install_large
          - app_install_minimal
          - dht_sync_lag
          - validation_receipts
          - write_get_agent_activity
          - write_validated_must_get_agent_activity
          - two_party_countersigning
          - zero_arc_create_data
          - zero_arc_create_data_validated
          - zero_arc_create_and_read
          - full_arc_create_validated_zero_arc_read
          - mixed_arc_get_agent_activity
          - mixed_arc_must_get_agent_activity

    env:
      RUN_ID: ${{ matrix.job-name }}_${{ github.run_id }}

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.commit-hash || github.sha }}

      - name: Read Nomad Job Variables
        id: read-nomad-vars
        run: |
          JOB_VARS_FILE="${{ inputs.nomad-job-variant-directory }}/vars/${{ matrix.job-name }}.json"
          NOMAD_VAR_DURATION="$(jq -e -r '.duration' "$JOB_VARS_FILE")"
          NOMAD_VAR_SCENARIO_NAME="$(jq -e -r '.scenario_name' "$JOB_VARS_FILE")"
          # Parse required nodes count from length of 'behaviours' list, or else default to 1.
          REQUIRED_NODES="$(jq -e -r '.behaviours // 1 | length' "$JOB_VARS_FILE")"

          echo "duration=$NOMAD_VAR_DURATION" >> "$GITHUB_OUTPUT"
          echo "scenario_name=$NOMAD_VAR_SCENARIO_NAME" >> "$GITHUB_OUTPUT"
          echo "required_nodes=$REQUIRED_NODES" >> "$GITHUB_OUTPUT"

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: holochain-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Nomad Job
        run: |
          nix run .#generate-nomad-jobs -- --job-name ${{ matrix.job-name }} --job-variant-path ${{ inputs.nomad-job-variant-directory }}

      - name: Build scenario
        run: nix build .#packages.x86_64-linux.${{ steps.read-nomad-vars.outputs.scenario_name }}

      - name: Upload scenario to bucket
        id: upload-scenario
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_SECRET }}
          AWS_DEFAULT_REGION: hel1
          AWS_ENDPOINT_URL: https://hel1.your-objectstorage.com
          S3_BUCKET_NAME: wind-tunnel-public-artifacts
        run: |-
          OUT_PATH="${S3_BUCKET_NAME}/run-artifacts/${{ github.run_id }}/${{ steps.read-nomad-vars.outputs.scenario_name }}.zip"
          nix run .#awscli-s3 cp ./result/${{ steps.read-nomad-vars.outputs.scenario_name }}.zip "s3://${OUT_PATH}"

          echo "scenario_download_url=${AWS_ENDPOINT_URL}/${OUT_PATH}" >> "$GITHUB_OUTPUT"
          echo "Uploaded run scenario artifact to ${AWS_ENDPOINT_URL}/${OUT_PATH}" >> "$GITHUB_STEP_SUMMARY"

      - name: Wait For Minimum Free Nodes
        timeout-minutes: 30
        env:
          NIXPKGS_ALLOW_UNFREE: 1
          NOMAD_ADDR: https://nomad-server-01.holochain.org:4646
          NOMAD_CACERT: "${{ github.workspace }}/nomad/server-ca-cert.pem"
          NOMAD_TOKEN: ${{ secrets.NOMAD_ACCESS_TOKEN }}
          REQUIRED_NODES: ${{ steps.read-nomad-vars.outputs.required_nodes }}
        run: |
          echo "Waiting for $REQUIRED_NODES node(s) to be free"
          while true; do
              count=$(nix run --impure --inputs-from . nixpkgs#nomad -- node status -allocs | awk 'NR > 1 {if (($8 == "ready") && ($9 == 0)) count+=1} END {print count}')
              if (( ${count:-0} >= $REQUIRED_NODES )); then
                  break
              else
                  echo -n "."
              fi
              sleep 5
          done
          echo "done"

      - name: Run Nomad Job
        id: run-nomad-job
        env:
          NIXPKGS_ALLOW_UNFREE: 1
          NOMAD_ADDR: https://nomad-server-01.holochain.org:4646
          NOMAD_CACERT: "${{ github.workspace }}/nomad/server-ca-cert.pem"
          NOMAD_TOKEN: ${{ secrets.NOMAD_ACCESS_TOKEN }}
          NOMAD_VAR_scenario_url: ${{ steps.upload-scenario.outputs.scenario_download_url }}
          NOMAD_VAR_run_id: ${{ env.RUN_ID }}
          NOMAD_VAR_holochain_bin_url: ${{ inputs.holochain-bin-url }}
        run: |-
          set -euo pipefail
          JOB_NAME="${{ matrix.job-name }}"
          nomad_output=$(nix run --impure --inputs-from . nixpkgs#nomad -- job run ${{ inputs.nomad-job-variant-directory }}/jobs/${JOB_NAME}.nomad.hcl)
          echo "$nomad_output"
          echo "Ran ${JOB_NAME} with run ID ${RUN_ID}" >> "$GITHUB_STEP_SUMMARY"
          alloc_ids=$(echo "$nomad_output" | grep -oP --color=never 'Allocation "\K[0-9a-f]+(?=" created)' | paste -sd ' ' -)
          if [ -z "$alloc_ids" ]; then
            echo "Failed to extract allocation IDs from Nomad job output"
            exit 1
          fi

          echo "alloc_ids=$alloc_ids" >> "$GITHUB_OUTPUT"
          echo "started_at=$(date +%s)" >> "$GITHUB_OUTPUT"
          echo "job_name=${JOB_NAME}" >> "$GITHUB_OUTPUT"

      - name: Save alloc_ids to file
        run: |
          started_at=${{ steps.run-nomad-job.outputs.started_at }}
          nix develop --command ./nomad/scripts/ci_allocs.sh make_allocs_csv alloc_ids.csv "${{ inputs.nomad-job-variant-directory }}/vars" "${{ matrix.job-name }}" "${{ steps.read-nomad-vars.outputs.scenario_name }}" "$RUN_ID" "${started_at}" "${{ steps.run-nomad-job.outputs.alloc_ids }}"

      - name: Upload alloc_ids
        uses: actions/upload-artifact@v6
        with:
          name: alloc_ids_${{ matrix.job-name }}
          path: alloc_ids.csv

      - name: Persist matrix job outputs for subsequent job use
        uses: cloudposse/github-action-matrix-outputs-write@v1
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ env.RUN_ID }}
          outputs: |-
            alloc_ids: "${{ steps.run-nomad-job.outputs.alloc_ids }}"
            run_id: "${{ env.RUN_ID }}"
            job_name: "${{ steps.run-nomad-job.outputs.job_name }}"
            started_at: "${{ steps.run-nomad-job.outputs.started_at }}"
            duration: "${{ steps.read-nomad-vars.outputs.duration }}"

  collect-github-matrix-outputs:
    name: Collect Run Ids
    runs-on: ubuntu-latest
    needs: run-scenarios
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: run-scenarios

      - name: Restructure merged output
        id: restructure
        run: |
          echo '${{ steps.read.outputs.result }}' | jq -c -R 'fromjson |
            (.alloc_ids | keys) as $keys |
            [ $keys[] as $key |
              {
                job_name: .job_name[$key],
                run_id: .run_id[$key],
                started_at: .started_at[$key],
                duration: .duration[$key],
                alloc_ids: .alloc_ids[$key]
              }
            ]' > out.json

          echo "result=$(cat out.json)" >> $GITHUB_OUTPUT

    outputs:
      result: "${{ steps.restructure.outputs.result }}"

  wait-for-jobs:
    name: Wait for Nomad jobs to finish
    runs-on: ubuntu-latest
    needs: collect-github-matrix-outputs
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.collect-github-matrix-outputs.outputs.result) }}
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: holochain-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Wait for all allocations in job
        env:
          NOMAD_ADDR: https://nomad-server-01.holochain.org:4646
          NOMAD_CACERT: "${{ github.workspace }}/nomad/server-ca-cert.pem"
          NOMAD_TOKEN: ${{ secrets.NOMAD_ACCESS_TOKEN }}
        run: |-
          # get started at
          started_at=${{ matrix.started_at }}
          duration=${{ matrix.duration }}
          current_time=$(date +%s)
          buffer=600
          # set timeout to $duration + $buffer (seconds $buffer) - ($current_time - $started_at)
          remaining=$(( duration - (current_time - started_at) ))
          export TIMEOUT=$(( $remaining + $buffer ))
          export TIMEOUT=$(( TIMEOUT < 0 ? $duration + $buffer : TIMEOUT )) # if timeout is negative; set to `duration + buffer`
          echo "Timeout for ${{ matrix.job_name }}: $TIMEOUT seconds (started_at: ${started_at}; duration: ${duration})"
          nix develop --command ./nomad/scripts/wait_for_jobs.sh ${{ matrix.job_name }} ${{ matrix.alloc_ids }}

  run-summary:
    name: Generate a summary of all scenarios
    runs-on: ubuntu-latest
    needs: wait-for-jobs
    if: ${{ !cancelled() }}
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: holochain-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Download all alloc_ids
        uses: actions/download-artifact@v7
        with:
          pattern: "alloc_ids_*"

      - name: Combine alloc_ids files into single
        run: cat alloc_ids_*/alloc_ids.csv >> alloc_ids.csv

      - name: Prepare run summary
        env:
          NIXPKGS_ALLOW_UNFREE: 1
          NOMAD_ADDR: https://nomad-server-01.holochain.org:4646
          NOMAD_CACERT: "${{ github.workspace }}/nomad/server-ca-cert.pem"
          NOMAD_TOKEN: ${{ secrets.NOMAD_ACCESS_TOKEN }}
          RUN_SUMMARY_PATH: ./run_summary.jsonl
        run: |
          nix develop --command ./nomad/scripts/ci_allocs.sh generate_run_summary alloc_ids.csv "$RUN_SUMMARY_PATH"
          cat "$RUN_SUMMARY_PATH" >> "$GITHUB_STEP_SUMMARY"

      - name: Cache summariser
        uses: actions/cache@v5
        with:
          path: |
            target/
            .cargo/registry
            .cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run summariser
        if: ${{ !cancelled() }}
        env:
          INFLUX_HOST: "https://ifdb.holochain.org"
          INFLUX_BUCKET: "windtunnel"
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          RUST_LOG: debug
          IGNORE_SUMMARY_ERRORS: ${{ inputs.ignore-summary-errors }}
        run: nix develop --command cargo run --release --bin holochain-summariser

      - name: Generate summary id for artifacts
        id: generate-summary-id
        run: |
          SUMMARY_TIMESTAMP=$(date +%s)
          SUMMARY_ID="$(date -d @${SUMMARY_TIMESTAMP} '+%Y%m%d%H%M%S').${{ inputs.commit-hash || github.sha }}"
          echo "summary_timestamp=$SUMMARY_TIMESTAMP" >> "$GITHUB_OUTPUT"
          echo "summary_id=$SUMMARY_ID" >> "$GITHUB_OUTPUT"

      - name: Checkout latest runs list from GitHub Pages
        if: inputs.enable-summary-uploads
        uses: actions/checkout@v6
        with:
          ref: gh-pages
          path: site
          sparse-checkout: _includes/runs-list.md

      - name: Generate summary visualiser
        id: generate-summary-visualiser
        run: |
          mkdir -p ./site
          OUTPUT_FILE="run.${{ steps.generate-summary-id.outputs.summary_id }}.html"

          # The summary visualiser can only take one file at a time,
          # but only one summariser report JSON file is fed to it in a run.
          # The wildcard here is because we don't know the name of the file.
          nix run .#generate-summary-visualiser ./summariser-report-*.json "./site/${OUTPUT_FILE}"

          echo "output_file=${OUTPUT_FILE}" >> "$GITHUB_OUTPUT"

      - name: Add summary to runs list
        if: inputs.enable-summary-uploads
        run: |
          SUMMARY_TIMESTAMP_HUMAN="$(date -d @${{ steps.generate-summary-id.outputs.summary_timestamp }} '+%Y-%m-%d %H:%M:%S')"
          LIST_ITEM_STRING="- [${SUMMARY_TIMESTAMP_HUMAN} (${{ inputs.commit-hash || github.sha }})](${{ steps.generate-summary-visualiser.outputs.output_file }})"

          # Prepend to runs list
          sed -i "1i${LIST_ITEM_STRING}" ./site/_includes/runs-list.md

      - name: Push summary visualiser html and updated runs list to GitHub Pages
        if: inputs.enable-summary-uploads
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_dir: ./site/
          publish_branch: gh-pages
          keep_files: true
          enable_jekyll: true

      - name: Upload run summary to bucket
        if: inputs.enable-summary-uploads
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_SECRET }}
          AWS_DEFAULT_REGION: fsn1
          AWS_ENDPOINT_URL: https://fsn1.your-objectstorage.com
          S3_BUCKET_NAME: wind-tunnel-artifacts
        run: |-
          OUT_PATH="${S3_BUCKET_NAME}/summariser-reports/${{ steps.generate-summary-id.outputs.summary_id }}.json"
          nix run .#awscli-s3 cp summariser-report-*.json "s3://${OUT_PATH}"

          echo "Uploaded run summary to ${AWS_ENDPOINT_URL}/${OUT_PATH}" >> "$GITHUB_STEP_SUMMARY"

  cleanup:
    name: Cleanup scenario artifacts
    runs-on: ubuntu-latest
    needs: wait-for-jobs
    if: always()
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: holochain-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Delete scenarios from bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_SECRET }}
          AWS_DEFAULT_REGION: hel1
          AWS_ENDPOINT_URL: https://hel1.your-objectstorage.com
          S3_BUCKET_NAME: wind-tunnel-public-artifacts
        run: |-
          nix run .#awscli-s3 -- rm "s3://${S3_BUCKET_NAME}/run-artifacts/${{ github.run_id }}" --recursive

          echo "Deleted ${AWS_ENDPOINT_URL}/${S3_BUCKET_NAME}/run-artifacts/${{ github.run_id }}" >> "$GITHUB_STEP_SUMMARY"
